spring:
  application:
    name: payroll-application
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password: ''
    url: jdbc:h2:file:./demodb
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions:  true
